name: CI/CD Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "*" ]
    paths-ignore:
      - 'README.md'
      - 'docs/**'
      - 'LICENSE'
      - 'CONTRIBUTING.md'
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Fazer checkout do código
        uses: actions/checkout@v4
      - name: Configurar Java 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'
      - name: Executar testes
        run: mvn -B verify --file pom.xml